name: Manage outdated dependencies and create issue

on: 
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  check-outdated-dependencies:
    runs-on: macos-latest
    name: Check outdated dependencies and create issue if it doesn't exist
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Check outdated dependencies and create issue
        id: check-outdated-dependencies-and-create-issue
        uses: rudderlabs/github-action-updated-dependencies-notifier@main
        with:
          outdated-dependency-names: "com.braze:android-sdk-ui"
          directory: "braze/build.gradle"
          title: "fix: update Braze SDK to the latest version"
          assignee: "@rudderlabs/sdk-android"
          labels: "outdatedDependency"
          color: "FBCA04"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the github issue url
        if: steps.check-outdated-dependencies-and-create-issue.outputs.issue-url != ''
        run: echo "The Github issue url is ${{ steps.check-outdated-dependencies-and-create-issue.outputs.issue-url }}"
